### PR TITLE
Examples System

### PR DESCRIPTION
**Pull request by Patabugen**
I've added the basis for being able to easily show example of using FormManager alongside their PHP and HTML output.

To add an example simple create a file in the `examples/example` directory with a short example at the top, and the form code below.

To really see the examples it's best to be able to run the code, I've hosted a copy of the examples here:

http://pata.cat/tools/form-manager/examples/index.php

which should be online for the foreseeable future. but anybody is welcome to host a new copy (or perhaps setup a git-pages).

Feel free to suggest better ways to achieve any of these examples.

### CODE REVIEW

**Comment by Patabugen** [comment]
I've added some examples which use the bootstrap extension, I didn't feel it was necessary to have a separate place just for them so I've just prefixed the bootstrap example with `bootstrap`.

**Comment by oscarotero** [comment]
Hi. Thank you for your contribution!
(are you catalan? I'm galician!)
Your example template looks great. The only thing I see is that some examples are not correct.
For example, to use multiple submit buttons (with the same name, but different value) you must use `F::choose()`:

```php
$form['submit'] = F::choose([
    'save' => F::button()->label('Save'),
    'saveAndCreate' => F::button()->label('Save and create another')
]);
```

This generate somethink similar to:
```html
<button name="submit" value="save">Save</button>
<button name="submit" value="saveAndCreate">Save and create another</button>
```

**Comment by Patabugen** [comment]
Hey Oscar,

I'm not Catalan - all English I'm afraid!

I'm not sure I can see what's different in your email from my example, aside from me using $form->add rather than $form[] to add the choose to the form.

Where I'm using the Form Manager I'm creating the elements and then adding them, which is why my examples use $add rather than passing them into the builder in the first place.

--
Sami

--
Sami
On 19/05/2015 15:13:03, Oscar Otero <notifications@github.com> wrote:
Hi. Thank you for your contribution!
(are you catalan? I'm galician!)
Your example template looks great. The only thing I see is that some examples are not correct.
For example, to use multiple submit buttons (with the same name, but different value) you must use F::choose():
$form['submit'] = F::choose([ 'save' => F::button()->label('Save'), 'saveAndCreate' => F::button()->label('Save and create another') ]);
This generate somethink similar to:
<button name="submit" value="save">Save</button> <button name="submit" value="saveAndCreate">Save and create another</button>

**Comment by oscarotero** [comment]
Ok. I said that because the website where the examples are hosted is in a catalan domain (http://pata.cat/) :smile: 
And about the example, yes, you're right. I saw a group where there was a choose.
Maybe insert the elements directly, instead create first, is visually clearer, I think.
Anyway, I think it's a great work. Can I merge it?

**Comment by Patabugen** [comment]
Ahh yes, I'm afraid not!

I actually find it clearer to create the elements and then put them together, but horses for courses - I'll change them to match the documentation if you prefer?

Go ahead and merge if you're happy with it.

--
Sami
On 19/05/2015 15:26:08, Oscar Otero <notifications@github.com> wrote:
Ok. I said that because the website where the examples are hosted is in a catalan domain (http://pata.cat/ [http://pata.cat/]) [:smile:]
And about the example, yes, you're right. I saw a group where there was a choose.
Maybe insert the elements directly, instead create first, is visually clearer, I think.
Anyway, I think it's a great work. Can I merge it?

**Comment by oscarotero** [comment]
Merged!. Maybe I'll made some changes (related with the styles and that stuff) :cat:

**Pull request merged**
